export const SET_COURSES = 'SET_COURSES';
export const DELETE_COURSE = 'DELETE_COURSE';
export const CREATE_COURSE = 'CREATE_COURSE';
export const FETCH_COURSE = 'FETCH_COURSE';
export const SAVE_COURSE = 'SAVE_COURSE';
export const CHANGE_CURRENT_COURSE_TITLE = 'CHANGE_CURRENT_COURSE_TITLE';
